# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "AnasOne"
license = "MIT"
licenselink = "http://htdvisser.mit-license.org/"
description = "AnasOne is a theme to build onepage-style homesite for Anas's product."
homepage = "https://vr.anasit.com/"
tags = ["homesite", "syntax highlighting"]
features = ["homesite", "syntax highlighting"]
min_version = 0.15

[author]
  name = "Ryane Max"
  homepage = "https://ryanemax.github.io/"
